sudo: required
os: linux
cache: false
language: bash
services:
- docker
jobs:
  include:
  - stage: build
    if: tag IS present
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build --target prod-stage -t devstroke/www:$TRAVIS_TAG -f docker/Dockerfile .
    - docker tag devstroke/renderer:$TRAVIS_TAG devstroke/renderer:latest
    - docker push devstroke/renderer:$TRAVIS_TAG
    - docker push devstroke/renderer:latest
    - ssh -ti /tmp/deploy_key devstroke@devstroke.io devstroke-renderer $TRAVIS_TAG
before_install:
- openssl aes-256-cbc -K $encrypted_dc3afb36faf0_key -iv $encrypted_dc3afb36faf0_iv
  -in travis/deploy_key.enc -out /tmp/deploy_key -d
- chmod 600 /tmp/deploy_key
addons:
  ssh_known_hosts:
  - devstroke.io
